image: ubuntu

services:
  - docker

notifications:
  - provider: Slack
    auth_token:
      secure: /YatG4lcTPFO0Jrz2fN9YVEOWca9G3wJ9LCWQjUD1oz6dfLAzYEqDqb7qqtj5Oje2NIVlms8uRwdUUtxjER6pQ==
    channel: "#smart-on-fhir"

build_script:
  - docker build -t appTest -f ./AppTest/Dockerfile .
